services:
  postgres:
    image: postgres:16-alpine
    container_name: transacao-bancaria-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: transacao_bancaria
      POSTGRES_USER: transacao_bancaria
      POSTGRES_PASSWORD: transacao_bancaria_senha

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transacao_bancaria -d transacao_bancaria"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: transacao-bancaria-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/transacao_bancaria
      SPRING_DATASOURCE_USERNAME: transacao_bancaria
      SPRING_DATASOURCE_PASSWORD: transacao_bancaria_senha
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate

volumes:
  postgres_data: