spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transacao_bancaria
    username: transacao_bancaria
    password: transacao_bancaria_senha
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration