spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digital_bank
    username: digital_bank_user
    password: digital_bank_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration